#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sakregister.Classes.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CSImport-Lokal")]
	public partial class CSImportDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSakregistret(Sakregistret instance);
    partial void UpdateSakregistret(Sakregistret instance);
    partial void DeleteSakregistret(Sakregistret instance);
    #endregion
		
		
		
		public CSImportDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSImportDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSImportDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CSImportDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Sakregistret> Sakregistrets
		{
			get
			{
				return this.GetTable<Sakregistret>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sakregistret")]
	public partial class Sakregistret : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Ar;
		
		private string _Ord;
		
		private string _Arende;
		
		private string _Betankande;
		
		private string _Skrivelse;
		
		private string _Protokoll;
		
		private System.Nullable<System.DateTime> _Created;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnArChanging(string value);
    partial void OnArChanged();
    partial void OnOrdChanging(string value);
    partial void OnOrdChanged();
    partial void OnArendeChanging(string value);
    partial void OnArendeChanged();
    partial void OnBetankandeChanging(string value);
    partial void OnBetankandeChanged();
    partial void OnSkrivelseChanging(string value);
    partial void OnSkrivelseChanged();
    partial void OnProtokollChanging(string value);
    partial void OnProtokollChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    #endregion
		
		public Sakregistret()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ar", DbType="NVarChar(50)")]
		public string Ar
		{
			get
			{
				return this._Ar;
			}
			set
			{
				if ((this._Ar != value))
				{
					this.OnArChanging(value);
					this.SendPropertyChanging();
					this._Ar = value;
					this.SendPropertyChanged("Ar");
					this.OnArChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ord", DbType="NVarChar(255)")]
		public string Ord
		{
			get
			{
				return this._Ord;
			}
			set
			{
				if ((this._Ord != value))
				{
					this.OnOrdChanging(value);
					this.SendPropertyChanging();
					this._Ord = value;
					this.SendPropertyChanged("Ord");
					this.OnOrdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Arende", DbType="NVarChar(255)")]
		public string Arende
		{
			get
			{
				return this._Arende;
			}
			set
			{
				if ((this._Arende != value))
				{
					this.OnArendeChanging(value);
					this.SendPropertyChanging();
					this._Arende = value;
					this.SendPropertyChanged("Arende");
					this.OnArendeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Betankande", DbType="NVarChar(255)")]
		public string Betankande
		{
			get
			{
				return this._Betankande;
			}
			set
			{
				if ((this._Betankande != value))
				{
					this.OnBetankandeChanging(value);
					this.SendPropertyChanging();
					this._Betankande = value;
					this.SendPropertyChanged("Betankande");
					this.OnBetankandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Skrivelse", DbType="NVarChar(255)")]
		public string Skrivelse
		{
			get
			{
				return this._Skrivelse;
			}
			set
			{
				if ((this._Skrivelse != value))
				{
					this.OnSkrivelseChanging(value);
					this.SendPropertyChanging();
					this._Skrivelse = value;
					this.SendPropertyChanged("Skrivelse");
					this.OnSkrivelseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Protokoll", DbType="NVarChar(255)")]
		public string Protokoll
		{
			get
			{
				return this._Protokoll;
			}
			set
			{
				if ((this._Protokoll != value))
				{
					this.OnProtokollChanging(value);
					this.SendPropertyChanging();
					this._Protokoll = value;
					this.SendPropertyChanged("Protokoll");
					this.OnProtokollChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
